import React from 'react';
import { LegalLayout } from './LegalLayout';
import { LegalPlaceholder } from './LegalPlaceholder';
import { Link } from '../../router';

export const PrivacyPolicy: React.FC = () => {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="14 September 2026">
      <section>
        <h2>Who we are</h2>
        <p>
          This site is operated by <strong>Nexa Sports Management Ltd</strong>, registered in England
          and Wales under company number <LegalPlaceholder>COMPANY NUMBER — TBC</LegalPlaceholder>,
          registered office at <LegalPlaceholder>REGISTERED OFFICE ADDRESS — TBC</LegalPlaceholder>. We
          are the data controller for the personal data described below.
        </p>
      </section>

      <section>
        <h2>What we collect</h2>
        <p>When you use the "Player Liaison" inquiry form, we collect:</p>
        <ul>
          <li>Your name or title</li>
          <li>Current club or competitive tier</li>
          <li>Your direct contact details (phone, email, or messaging handle you provide)</li>
          <li>Any message or notes you include</li>
          <li>Which part of the site the inquiry came from, and the time it was submitted</li>
        </ul>
        <p>
          We do not currently use analytics or advertising cookies, so we do not collect browsing
          behaviour beyond standard server logs (e.g. IP address, browser type) generated by normal
          web hosting. See our <Link to="/cookies">Cookie Notice</Link> for detail.
        </p>
      </section>

      <section>
        <h2>How we use it</h2>
        <p>
          We use inquiry data solely to respond to and evaluate representation inquiries. Our legal
          basis is legitimate interest — responding to unsolicited business inquiries you have chosen
          to send us. We do not use this data for marketing, and we do not sell or rent it to anyone.
        </p>
      </section>

      <section>
        <h2>Where it's stored, and who else sees it</h2>
        <p>
          Submissions are stored on our hosting infrastructure. If email notifications are configured,
          a copy is also sent via <strong>Resend</strong>, a third-party email delivery service, to our
          internal inbox. Resend acts as our data processor for this purpose and may process data on
          servers outside the UK/EEA; where that happens, appropriate safeguards (such as Standard
          Contractual Clauses) apply.
        </p>
        <p>
          This page's fonts are loaded from Google Fonts' servers, which may log your IP address as
          part of delivering the font files. No account or profile is built from this.
        </p>
      </section>

      <section>
        <h2>How long we keep it</h2>
        <p>
          We retain inquiry submissions for as long as needed to evaluate and follow up on them. You
          can ask us to delete your submission at any time — see "Your rights" below.
        </p>
      </section>

      <section>
        <h2>Your rights</h2>
        <p>Under UK GDPR, you have the right to:</p>
        <ul>
          <li>Ask what personal data we hold about you</li>
          <li>Ask us to correct or delete it</li>
          <li>Ask us to restrict or object to our use of it</li>
          <li>Request a copy in a portable format</li>
          <li>
            Complain to the{' '}
            <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer">
              UK Information Commissioner's Office (ICO)
            </a>{' '}
            if you believe we've mishandled your data
          </li>
        </ul>
        <p>
          To exercise any of these rights, contact us at{' '}
          <LegalPlaceholder>PRIVACY CONTACT EMAIL — TBC</LegalPlaceholder>.
        </p>
      </section>

      <section>
        <h2>Confidentiality of representation inquiries</h2>
        <p>
          Submitting the inquiry form is a preliminary, non-binding expression of interest — it does
          not itself create a representation relationship or a non-disclosure obligation. Confidential
          handling of a formal client relationship is governed separately by our{' '}
          <Link to="/client-discretion-policy">Client Discretion Policy</Link> and any signed
          representation agreement.
        </p>
      </section>

      <section>
        <h2>Children</h2>
        <p>
          This site is directed at football clubs, professional players, and their representatives. We
          do not knowingly collect personal data from children through the general inquiry form.
        </p>
      </section>

      <section>
        <h2>Changes to this policy</h2>
        <p>
          We may update this policy from time to time. The "last updated" date at the top of this page
          reflects the most recent revision.
        </p>
      </section>

      <section>
        <h2>Contact us</h2>
        <p>
          For any question about this policy or your data, contact{' '}
          <LegalPlaceholder>PRIVACY CONTACT EMAIL — TBC</LegalPlaceholder>.
        </p>
      </section>
    </LegalLayout>
  );
};
